import { StyleSheet, Platform } from 'react-native';

const PRIMARY = '#4f46e5';

export const styles = StyleSheet.create({
  root: { flex: 1, flexDirection: 'row', backgroundColor: '#f3f4f6', position: 'relative' },
  sidebar: { width: 220, backgroundColor: '#0f172a', paddingVertical: 12, paddingHorizontal: 10 },
  sidebarCollapsed: { width: 72 },
  sidebarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sidebarTitle: { color: '#fff', fontSize: 16, fontWeight: '700' },
  collapseBtn: { padding: 6, borderRadius: 6, backgroundColor: 'rgba(255,255,255,0.06)' },
  collapseBtnText: { color: '#fff', fontSize: 14 },
  sidebarItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    marginBottom: 6,
  },
  sidebarItemActive: {
    backgroundColor: PRIMARY,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    elevation: 3,
  },
  sidebarIcon: { fontSize: 18, color: '#9ca3af', width: 28, textAlign: 'center' },
  sidebarText: { color: '#9ca3af', marginLeft: 8, fontSize: 14 },
  sidebarTextActive: { color: '#fff', fontWeight: '700' },
  sidebarFooter: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerUser: { color: '#9ca3af', fontSize: 12 },
  logoutBtn: { padding: 8 },
  logoutText: { color: '#fff', fontSize: 16 },
  sidebarScroll: { flex: 1 },
  sidebarIconWrapper: { width: 28, alignItems: 'center' },
  mainArea: { flex: 1, padding: 12 },
  topbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  projectTitle: { fontSize: 18, fontWeight: '800', color: '#111' },
  menuToggle: {
    padding: 8,
    marginRight: 8,
    backgroundColor: '#fff',
    borderRadius: 8,
    elevation: Platform.OS === 'android' ? 2 : 0,
  },
  menuToggleText: { fontWeight: '700' },
  search: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  topIcons: { flexDirection: 'row', alignItems: 'center' },
  iconButton: { padding: 8, marginLeft: 6, backgroundColor: '#fff', borderRadius: 8 },

  /* Controls */
  controls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    alignItems: 'center',
  },
  addBtn: {
    backgroundColor: PRIMARY,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
  },
  addBtnText: { color: '#fff', fontWeight: '700' },
  refreshBtn: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e6e9f2',
  },
  refreshBtnText: { color: '#374151', fontWeight: '700' },

  /* Table */
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#e5e7eb',
    padding: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    backgroundColor: '#fff',
  },
  tableCellView: { paddingHorizontal: 6, paddingVertical: 6, justifyContent: 'center' },
  tableCellText: { color: '#111827', fontSize: 14 },

  /* Card */
  card: {
    padding: 14,
    borderRadius: 10,
    backgroundColor: '#fff',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  socName: { fontSize: 16, fontWeight: '700', color: '#0f172a' },
  socMeta: { color: '#6b7280', marginTop: 6 },
  smallButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: PRIMARY,
    borderRadius: 6,
    marginRight: 6,
    marginTop: 4,
  },
  smallButtonText: { color: '#fff', fontSize: 12 },
  actionIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  actionIconText: { color: '#fff', fontSize: 14 },

  panel: { padding: 20 },
  panelTitle: { fontSize: 18, fontWeight: '800', marginBottom: 8 },
  panelText: { color: '#6b7280' },

  socCardsRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start' },
  socCard: {
    // allow responsive overrides; keep a max width for larger screens
    maxWidth: 280,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 10,
    marginRight: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  socCardTitle: { fontSize: 16, fontWeight: '800' },
  socCardSub: { color: '#6b7280', marginTop: 6 },
  socCardMeta: { color: '#374151', marginTop: 6, fontSize: 13 },

  /* Loading overlay */
  loadingOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.6)',
    zIndex: 10,
    elevation: 10,
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContent: { width: '92%', backgroundColor: '#fff', padding: 12, borderRadius: 10 },
  smallBtn: {
    backgroundColor: PRIMARY,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },

  modalInner: { flex: 1, padding: 20, backgroundColor: '#f8fafc' },
  modalTitle: { fontSize: 20, fontWeight: '800', marginBottom: 12 },
  input: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e6eef8',
  },
  modalActions: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  modalBtn: { paddingVertical: 12, paddingHorizontal: 20, borderRadius: 10 },
  modalBtnText: { color: '#fff', fontWeight: '700' },
  /* additional shared styles used by split screens */
  contentArea: { flex: 1 },
  scrollContent: { paddingVertical: 8 },
  socCardActions: { marginTop: 10, flexDirection: 'row', justifyContent: 'space-between' },
  smallBtnSuccess: {
    backgroundColor: '#10b981',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  smallBtnTextWhite: { color: '#fff' },
  flex1: { flex: 1 },
  panelCompact: { padding: 6, flex: 1 },
  flatlistFlex: { flex: 1 },
  flatlistContent: {},
  emptyListPadding: { padding: 12 },
  emptyListText: { color: '#6b7280' },
  profileActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 12 },
  smallBtnClose: {
    backgroundColor: '#ccc',
    marginRight: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  closeText: { color: '#111' },
  bottomTabContainer: {
    borderTopWidth: 1,
    borderColor: '#e6e9f2',
    backgroundColor: '#fff',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
});

export default styles;
