const db = require('../src/models');
const cloudinary = require('cloudinary').v2;
let puppeteer = null;
try { puppeteer = require('puppeteer'); } catch(e){ console.warn('puppeteer not available'); }

(async ()=>{
  try{
    await db.sequelize.authenticate();
    console.log('connected DB');
    // choose an agreement id that has null file_url
    const agreementId = '6e1608d3-5f8e-433c-8e82-e58aefe116e4';
    const agreement = await db.Agreement.findByPk(agreementId);
    if(!agreement){ console.error('agreement not found'); process.exit(1); }
    const tenant = await db.User.findByPk(agreement.tenantId);
    const owner = await db.User.findByPk(agreement.ownerId);
    const flat = await db.Flat.findByPk(agreement.flatId);
    const html = `
      <html><head><meta charset="utf-8"><title>Rent Agreement</title></head><body>
      <h2>Rent Agreement</h2>
      <p><strong>Owner:</strong> ${owner.name||''} (${owner.phone||''})</p>
      <p><strong>Owner address:</strong> ${owner.address||''}</p>
      <p><strong>Tenant:</strong> ${tenant.name||''} (${tenant.phone||''})</p>
      <p><strong>Tenant address:</strong> ${tenant.address||''}</p>
      <p><strong>Flat:</strong> ${flat.flat_no||''}</p>
      <p>Agreement generated by script.</p>
      </body></html>
    `;
    let uploadedUrl = null;
    if(puppeteer){
      try{
        console.log('launching puppeteer');
        const browser = await puppeteer.launch({ args:['--no-sandbox','--disable-setuid-sandbox'] });
        const page = await browser.newPage();
        await page.setContent(html,{waitUntil:'networkidle0'});
        const pdfBuffer = await page.pdf({format:'A4', printBackground:true});
        await browser.close();
        const pdfDataUrl = `data:application/pdf;base64,${pdfBuffer.toString('base64')}`;
        uploadedUrl = pdfDataUrl;
        console.log('pdf generated, size', pdfBuffer.length);
        // try cloudinary if configured
        if(process.env.CLOUDINARY_CLOUD_NAME && process.env.CLOUDINARY_API_KEY && process.env.CLOUDINARY_API_SECRET){
          try{
            const res = await cloudinary.uploader.upload(pdfDataUrl,{folder:'society_karbhar/agreements', resource_type:'raw'});
            uploadedUrl = res.secure_url || uploadedUrl;
            console.log('uploaded to cloudinary', uploadedUrl);
          }catch(e){ console.warn('cloud upload failed', e.message); }
        }
      }catch(e){ console.warn('puppeteer render failed', e && e.message); }
    } else {
      console.log('puppeteer not present, will upload HTML');
    }
    if(!uploadedUrl){
      const dataUrl = `data:text/html;base64,${Buffer.from(html).toString('base64')}`;
      uploadedUrl = dataUrl;
      if(process.env.CLOUDINARY_CLOUD_NAME && process.env.CLOUDINARY_API_KEY && process.env.CLOUDINARY_API_SECRET){
        try{
          const res = await cloudinary.uploader.upload(dataUrl,{folder:'society_karbhar/agreements'});
          uploadedUrl = res.secure_url || uploadedUrl;
          console.log('uploaded html to cloudinary', uploadedUrl);
        }catch(e){ console.warn('cloud html upload failed', e && e.message); }
      }
    }
    // update agreement
    agreement.file_url = uploadedUrl;
    agreement.start_date = new Date();
    await agreement.save();
    console.log('agreement updated with file_url');
    // create docs for tenant and owner
    const doc1 = await db.Document.create({ title:'Rent Agreement', file_url:uploadedUrl, file_type: uploadedUrl.startsWith('data:application/pdf')? 'application/pdf':'text/html', uploaded_by: agreement.tenantId, societyId: tenant.societyId });
    const doc2 = await db.Document.create({ title:'Rent Agreement (owner copy)', file_url:uploadedUrl, file_type: uploadedUrl.startsWith('data:application/pdf')? 'application/pdf':'text/html', uploaded_by: agreement.ownerId, societyId: tenant.societyId });
    console.log('created docs', doc1.id, doc2.id);
    process.exit(0);
  }catch(e){ console.error('error', e && (e.stack||e.message)); process.exit(1); }
})();
